### ISSUE TITLE
connection status of signalr

### ISSUE THREAD

**Issue by cnryb** [mandrewcito/signalrcore#10]
How to determine the connection status of signalr ?
When connection is closed , how to reconnection ?

**Comment by mandrewcito** [comment]
Hi,

Connection status is avaiable on the 'connection_alive' attribute.

Reconnection is automatic, in the [example with auth ](https://github.com/mandrewcito/signalrcore) you can see an example:

hub_connection = HubConnectionBuilder()
    .with_url(server_url)
    .with_automatic_reconnect({
        "type": "raw",
        "keep_alive_interval": 10,
        "reconnect_interval": 5,
        "max_attempts": 5
    ))
    .build()

**Comment by cnryb** [comment]
In the above example， the hub_connection have not attribute  'connection_alive' .

In my project , the automatic reconnection is failed. Can I reconnection use some method ？
My project is used abp (https://aspnetboilerplate.com/) .

**Comment by mandrewcito** [comment]
My mistake, 

connection status is placed on _hub.connection_alive.

Note that the connection status only be updated if a previous message is sended and it fails.(ping or message)

What kind of error is giving you reconnection? if you detail it i can investigate them, A sequence of steps to reproduce it will be usefull

**Comment by cnryb** [comment]
Ok, wait for me to write a simple example to reproduce the problem.
auto reconnection is very useful. but if automatic reconnection failed, now it seem thre is no way to solve the problem.
so, can we design this library like js signalr, can check status. like this:
```
//https://stackoverflow.com/questions/9334838/signalr-detect-connection-state-on-client/12825546#12825546
//{0: 'connecting', 1: 'connected', 2: 'reconnecting', 4: 'disconnected'}
if ($.connection.hub.state == 1) {
    // Start the connection.
     $.connection.hub.start()
 }
```

**Comment by mandrewcito** [comment]
Okey, i mark it as a enhancement, i will create an attribute state and work with enums like in js. Thanks!

**Comment by mandrewcito** [comment]
On the new version i will include on_connect and on_disconnect callbacks and a connection state like javascript, for enabling an 'manual' reconnection.
