### ISSUE TITLE
Callback on connection established

### ISSUE THREAD

**Issue by meirkr** [mandrewcito/signalrcore#11]
**Is your feature request related to a problem? Please describe.**
Since the ".start()" function takes long, my chat (demo) app starts to send messages to the server (and other clients), but no callback arrives back from the server.
I guess because the connection is still being established including handshake.

I was based on your example and made my own test app for chat.
GH: https://github.com/meirkr/signalr_pythom
To reproduce, 

1. start one or more web clients [https://meirkr.com](https://meirkr.com)
2. Clone my ripo above and run the code.
OR:
using docker:
`docker run --rm -it meirkr/signalr_python`
3. Right after inserting nick, try immediately to type some messages from that python client or even the other web clients. Sometimes it arrives fast, but sometimes (and most of times) it takes around 5-10 seconds till the messages are arrived (till then, the messages are just skipped)

**Describe the solution you'd like**
In angular signalr client, there is a possibility to get a trugger when the async start is completed, I assume inclusing the handshake.
`      this._hubConnection
      .start()
      .**then(() => this.OnConnected())**
      .catch(err => {
        this.connected = false;
        console.log('Error while establishing connection :(' + err);
        setTimeout(() => this.reconnect(), 5000);
      });
`
Is there a possibility to get something similar?

**Comment by mandrewcito** [comment]
On the new version i will include on_connect and on_disconnect callbacks and a connection state like javascript, for enabling an 'manual' reconnection. This will allow you to code some logic for prevent sending messages until the connection where fully stablished right?

**Comment by meirkr** [comment]
Correct.

בתאריך יום ג׳, 20 באוג׳ 2019, 18:45, מאת Andrés Baamonde Lozano ‏<
notifications@github.com>:
