### ISSUE TITLE
Add additional Header params

### ISSUE THREAD

**Issue by scervellera** [mandrewcito/signalrcore#13]
Hello,
is there a chance to insert additional parameter in header?

**Comment by mandrewcito** [comment]
On the version 0.7.8 will be possible:

syntax will be like this:

>         self.connection = HubConnectionBuilder()\
            .with_url(self.server_url,
            options={
                "access_token_factory": self.login,
                "headers": {
                    "mycustomheader": "mycustomheadervalue"
                }
            })\
            .configure_logging(logging.DEBUG)\
            .with_automatic_reconnect({
                "type": "raw",
                "keep_alive_interval": 10,
                "reconnect_interval": 5,
                "max_attempts": 5
            }).build()
