### ISSUE TITLE
Doesn't work with https

### ISSUE THREAD

**Issue by softsan** [mandrewcito/signalrcore#14]
**Describe the bug**
It doesn't work when hub server is running on https and getting following error:
`scheme https is invalid <class 'ValueError'>`

I am connecting it with` ws://mychathost/chatHub`, so if my chatHub is running on `http` then its working fine, but not on `https`.
 

**Additional context**
version: signalrcore 0.7.6

**Comment by mandrewcito** [comment]
Is your certificate self signed? i just add on version 0.7.9 an option param which enables ignore ssl cert 

> hub_connection = HubConnectionBuilder()\
>    .with_url(server_url, options={
>        "access_token_factory": lambda: signalr_core_example_login(login_url, username, password),
>        "verify_ssl": False
>    }).with_automatic_reconnect({
>        "type": "interval",
>        "keep_alive_interval": 10,
>        "intervals": [1, 3, 5, 6, 7, 87, 3]
>    })\
>    .build()
