### ISSUE TITLE
SignalRCore + Azure SignalR howto

### ISSUE THREAD

**Issue by vatjjar** [mandrewcito/signalrcore#15]
**Is your feature request related to a problem? Please describe.**
A clear example how to connect to a named service, e.g. Azure SignalR

**Describe the solution you'd like**
Setting up a SignalR service in Azure is trivial. What you get is a connection string with hostname and primary key. It is unclear how this needs to be configured using signalrcore to establish a connection to the service. A "Azure + SignalRCore step-by-step" -guide would solve the problem (and help signalrcore adoption greatly)

**Describe alternatives you've considered**
I've tried to configure this in various ways, but all seems to fail.

**Comment by mdkh1311** [comment]
I have been trying to get Azure SignalR working also. I think the issue is that Azure SignalR sends a redirect URL on a negotiate that then has to be posted to in order to finish the negotiation. I updated the negotiate code found in AuthHubConnection to the following code, and it is then able to connect. Please advise if this fix makes sense or if there is a better way to do it. Thanks

`
    def negotiateRequest(self):
        negotiate_url = Helpers.get_negotiate_url(self.url)
        logging.debug("Negotiate url:" + negotiate_url)
        response = requests.post(negotiate_url, headers=self.headers, verify=self.verify_ssl)
        if response.status_code != 200:
            raise HubError(response.status_code) if response.status_code != 401 else UnAuthorizedHubError()
        return response.json()

    def negotiate(self):
        data = self.negotiateRequest()
        if 'url' in data.keys() and 'accessToken' in data.keys():
            # Handle Azure SignalR Service Redirect
            self.url = data["url"]
            self.token = data["accessToken"]
            self.headers = {"Authorization": "Bearer " + self.token}
            data = self.negotiateRequest()
        self.url = Helpers.encode_connection_id(self.url, data["connectionId"])
`

**Comment by mandrewcito** [comment]
Okay, i will test it on azure these days thanks!

**Comment by mandrewcito** [comment]
Now, at version 0.8.4 azure integration and serverless functions can be used.
