### ISSUE TITLE
Synchronization with official semantic definitions

### ISSUE THREAD

**Issue by Loongle** [mandrewcito/signalrcore#2]
After I saw the example and finished the practical operation, I felt it was quite different from the official semantics

Using c # of Microsoft. AspNetCore. SignalR. Client, for example. The connection code is as follows
``` 
Connection = new HubConnectionBuilder()
          .WithUrl("http://localhost:55563/imessage/chart", (option) =>
{
     option.AccessTokenProvider = () => Task.Run(() => access_token);
 
}).Build();
```
Typescript connection example:
```
    this.hubConnection = new signalR.HubConnectionBuilder()
      .withUrl('http://localhost:55563/imessage/chart', {
        accessTokenFactory: () => this.tokenService.get().token
      }).build();
```
With this semantic definition, most developers can seamlessly migrate any language and use signalr.
All attribute method operations are basically the same

**Comment by mandrewcito** [comment]
Take a look to https://github.com/mandrewcito/signalrcore/tree/improvesyntax on this branch im trying to improve syntax!

**Comment by mandrewcito** [comment]
In this post i explain changes https://dev.to/mandrewcito/signalr-core-python-client-iv-improving-syntax-2pf6 , examples had been updated.
