### ISSUE TITLE
Not receiving return value from called Hub method

### ISSUE THREAD

**Issue by SaddamBInSyed** [mandrewcito/signalrcore#23]
Thanks for your work.

I have .net core server (hub methods) running.  
when client call the HUB methods then I am returning some value to the caller (client) form hub method.

but I am not receiving the same (returned value) at the client-side except None.

please advise.

**Comment by mandrewcito** [comment]
Did you try this ? 

Configure socket trace

HubConnectionBuilder()\
    .with_url(server_url,
    .configure_logging(logging.DEBUG, socket_trace=True) 

message appear on raw socket info?

**Comment by lhotamir** [comment]
@SaddamBInSyed I believe what you need is a callback for send function. I have added this option in #26

**Comment by mandrewcito** [comment]
https://pypi.org/project/signalrcore/0.8.6 ready for download, thank you @lhotamir !
