### ISSUE TITLE
MessagePack support

### ISSUE THREAD

**Issue by jacobowitz** [mandrewcito/signalrcore#32]
As far as I can see you currently only have support for JSON serialization format. I would love to also have this library support MessagePack.
It should also be fairly easy to add as @Apollo3zehn already implemented an async fork of your repo supporting MessagePack. I could of course also use his fork directly, but I didnt want to have the async part of his code. Thus I think a backport of his work would be very good. 
If everyone agrees, I can also do the PR for this repo based on the work of @Apollo3zehn.

**Comment by Apollo3zehn** [comment]
Please note that my `MessagePack` implementation only supports simple arguments (strings, numbers, datetime) and no complex object hierarchy. I have just no idea how to implement more complex object serialization/deserialization in python.

**Comment by mandrewcito** [comment]
Next weekend i will take a look to @Apollo3zehn implementation and reopen the msgpack branch i will make a try to do that complex objects´s serialization :D

**Comment by mandrewcito** [comment]
Hi!,

In https://github.com/mandrewcito/signalrcore/pull/44 there is the message pack implementation.

Thanks to @Apollo3zehn . I based implementation on your code, now my next steps will be related with serialization and improve library testing.
