### ISSUE TITLE
Reference to undefined function `_send_ping`

### ISSUE THREAD

**Issue by synapticarbors** [mandrewcito/signalrcore#34]
In perusing the source code for this library I noticed that there is a call to a method of the `BaseHubConnection` called `_send_ping()`

https://github.com/mandrewcito/signalrcore/blob/90540f388921a57ddd6a895fadae9527fd745674/signalrcore/hub/base_hub_connection.py#L315

This function is not defined within the source code and as far as I can tell, was never defined (searching through the git history).

I'm guessing it should probably be replaced by something like `self.send(PingMessage())`. I can open a pull request if this seems reasonable.

**Comment by mandrewcito** [comment]
Yes, 

Of course you can make a pull request.

Thank you!
