### ISSUE TITLE
Create proxy hub / invoke method

### ISSUE THREAD

**Issue by yrdeboer** [mandrewcito/signalrcore#36]
Hi, 

Thanks for making this code!

I'm trying to connect to a signalr server and in the docs it says this:

`To connect to the v3 socket, create a HubConnection to the socket URL ( https://socket-v3.bittrex.com/signalr) and create a hub proxy.`

Then they say (without more):

`To subscribe to one or more streams, simply invoke the Subscribe method
`

My questions are: could you please  supply examples in your documentation that help with:

1. Creating a hub "proxy", and
2. how to "simply invoke" a method?

Many thanks!

Ytsen.

**Comment by mandrewcito** [comment]
As i can read in the bittrex docs, signalr socket is a old signalr hub (https://bittrex.github.io/api/v3). it says:

"""
Like the existing v1 socket, the v3 socket is based on Microsoft ASP.net’s SignalR. We are not using ASP.net Core’s SignalR implementation at this time. As such, any existing SignalR client implementation working with the v1 socket should be able to be modified to work with the new v3 socket. If working in the .Net environment, the Microsoft.AspNet.SignalR.Client NuGet package is the recommended basis for a client implementation. The remainder of this section assumes you are working in C# using that library.
"""
 Asp signalr´s protocol is different from asp netcore signalr. Is this library that you are looking for https://pypi.org/project/signalr-client/?.

**Comment by yrdeboer** [comment]
Hi, thank you for your message! :)

I was using that library before, but it is very old, so I ventured to try
something different.

But that library will likely do the trick :)

Kind regards,

Ytsen.
