### ISSUE TITLE
no https support in 0.8.7?

### ISSUE THREAD

**Issue by 1337SEnergy** [mandrewcito/signalrcore#41]
```python
from signalrcore.hub_connection_builder import HubConnectionBuilder
import time;

hub = HubConnectionBuilder().with_url("https://socket-v3.bittrex.com/signalr", options={"verify_ssl": False}).with_automatic_reconnect({
"type": "interval",
"keep_alive_interval": 10,
"intervals": [1, 3, 5, 6, 7, 87, 3]
}).build();

def on_open():
	print("open");

def on_close():
	print("close");

hub.on_open(on_open);
hub.on_close(on_close);
hub.start();

while True:
	time.sleep(1);
```

this should, according to issue #14 work, but it doesn't, I also get the 
> scheme https is invalid <class 'ValueError'>

websocket-client is 0.54.0

edit: the only reason why I used ws-client 0.54.0 is because it says so in the readme, however signalr core installs ws-client 0.57 by default, as the requirements for it are websocket-client>=0.54.0 for some reason

**Comment by 1337SEnergy** [comment]
0.7.9 does not work either, and this one installs 0.57.0 ws-client as well

**Comment by mandrewcito** [comment]
As you can see on [bittrex docs](https://bittrex.github.io/api/v3), their signarl server is an classic signarl server. This library is a client for **singlar core**. Did you take a look to https://pypi.org/project/signalr-client/?
