### ISSUE TITLE
How to detect automatic re-connection?

### ISSUE THREAD

**Issue by PawelTroka** [mandrewcito/signalrcore#48]
we have `on_disconnect` and `on_connect` but these are not called when re-connection is automatic

**Comment by PawelTroka** [comment]
yeah, when re-connection fails then `on_close` is called, but when it does not fail then there is nothing like `on_reconnection`, right?

**Comment by morpheus65535** [comment]
I've create a pull request that implement this new `on_reconnect` event: https://github.com/mandrewcito/signalrcore/pull/60
