### ISSUE TITLE
[Errno 104] Connection reset by peer is received after some time

### ISSUE THREAD

**Issue by samy0392** [mandrewcito/signalrcore#5]
When I connect to server in chat example and keep the program running and after sometime I get 

> [Errno 104] Connection reset by peer

It seems like Signalrcore server kicks me out.

How can I handle this error?

**Comment by mandrewcito** [comment]
I classify it as a enhancement because library doesn't support reconnection at the moment. This week i will release the library with that feature.

**Comment by mandrewcito** [comment]
Version 0.7.0 now has this implemented.
