### ISSUE TITLE
websocket-client version

### ISSUE THREAD

**Issue by olalid** [mandrewcito/signalrcore#54]
**Describe the bug**
The signalrcore lib does not work fully with websocket-client later than 0.54.0, but requirements in setup.py is not enforcing that since requirement is websocket-client>=0.54.0

**To Reproduce**
1. Install signalr with pip.
2. websocket-client is installed with the newest available version.

**Expected behavior**
signalrcore should enforce the use of a compatible version of websocket-client.

**Comment by mandrewcito** [comment]
Hmm, seems that i forget to update setup.py thanks!!
