### ISSUE TITLE
'NoneType' object has no attribute 'connected'

### ISSUE THREAD

**Issue by tgreiser** [mandrewcito/signalrcore#59]
**Describe the bug**
With python3.8, signalrcore 0.9.2 and websocket-client 0.54.0 test socket closes almost immediately with:
```Websocket closing error: issuehttps://github.com/websocket-client/websocket-client/issues/449```

**To Reproduce**
1. Install signalrcore on linux
2. Run this example: https://api.tzkt.io/#section/Python-simple-client
3. Socket closes after about 2 events with error
```Websocket closing error: issuehttps://github.com/websocket-client/websocket-client/issues/449```

**Expected behavior**
I read the known issue, but I am running the version indicated (0.54.0).

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version 0.9.2

**Comment by mandrewcito** [comment]
Solved in  #61 , i will publish a tag soon!! thanks!
