### ISSUE TITLE
Can you publish this fix "Patched websocket transport to support websocket-client 1.0.0"

### ISSUE THREAD

**Issue by lovettchris** [mandrewcito/signalrcore#69]
When I pip install signalrcore I get 0.9.2 which is still dependent on websocket-client 0.54.0.  I'm running into the random websocket closing error...

**Comment by morpheus65535** [comment]
It's being used by more than 6000 instances of one of my project every day. I agree, it's time to merge it...

**Comment by marceloferrer** [comment]
Having the same issue here, I would love that release.

**Comment by lovettchris** [comment]
I've since switched to the awesome new [Azure Web Pub Sub service](https://docs.microsoft.com/en-us/azure/azure-web-pubsub/overview).  See [sample](https://github.com/Azure/azure-webpubsub/pull/334).

**Comment by marceloferrer** [comment]
> I've since switched to the awesome new [Azure Web Pub Sub service](https://docs.microsoft.com/en-us/azure/azure-web-pubsub/overview). See [sample](https://github.com/Azure/azure-webpubsub/pull/334).

So no python then?

**Comment by lovettchris** [comment]
> So no python then?

The  [Azure Web Pub Sub service](https://docs.microsoft.com/en-us/azure/azure-web-pubsub/overview) ships a python SDK and the sample I linked above is a python sample.

**Comment by mandrewcito** [comment]
released on version 0.9.3
