### ISSUE TITLE
Can you publish this fix "Patched websocket transport to support websocket-client 1.0.0"

### ISSUE THREAD

**Issue by ivfernandez** [mandrewcito/signalrcore#77]
When I pip install signalrcore I get 0.9.2 which is still dependent on websocket-client 0.54.0.
I'm running into the random websocket closing error...

Thank you very much!!

**Comment by marceloferrer** [comment]
Having the same issue here!

**Comment by mandrewcito** [comment]
Relased on pypi version 0.9.3 :)
