### ISSUE TITLE
BaseHubConnection object has no attribute 'sock' when exiting

### ISSUE THREAD

**Issue by meirkr** [mandrewcito/signalrcore#8]
**Describe the bug**
After I conncted successfully to my personal experimental hub, each time I exit (by typing a message "exit()"), I get the following failure:
--------------------------------------
>> ['kkkk', '']
exit()
Traceback (most recent call last):
  File "SignalrClient.py", line 28, in <module>
    hub_connection.stop()
  File "/signalrcore/signalrcore/hub_connection_builder.py", line 160, in stop
    self._hub.stop()
  File "/signalrcore/signalrcore/hub/base_hub_connection.py", line 71, in stop
    self.close()
  File "/usr/local/lib/python3.8/site-packages/websocket_client-0.56.0-py3.8.egg/websocket/_app.py", line 162, in close
    if self.sock:
AttributeError: 'BaseHubConnection' object has no attribute 'sock'
$
--------------------------------------

**To Reproduce**
1. See [my repo](https://github.com/meirkr/signalr_pythom/blob/master/README.md)
2. Instead of running the python, you can just run it using containerized docker: 
`docker run --rm -it meirkr/signalr_python`
3. When done chatting, type the message "exit()"

**Expected behavior**
Exit the app without error.

**Desktop (please complete the following information):**
 - OS: any os running pyhon 3 or docker

**Comment by mandrewcito** [comment]
Thanks for reporting of the error. Now is fixed on version 0.7.5.
