### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by wmmihaa** [mandrewcito/signalrcore#85]
"Hub is not running you **cand** send messages" at /signalrcore/hub/base_hub_connection.py line 127 should be "Hub is not running you cannot send messages" or "Hub is not running. Unable to transmit messages". Actually, the hub might very well be running but not accessible so perhaps "Cannot connect to SignalR hub. Unable to transmit messages"

Cheers

**Comment by mandrewcito** [comment]
I think that 'Cannot connect to SignalR hub. Unable to transmit messages' is the better choice, thanks!  

https://github.com/mandrewcito/signalrcore/commit/57a511bd11e6045cc1dae1801879523f4e3a15a4
